### ISSUE TITLE
Getting this error on deploy

### ISSUE THREAD

**Issue by lajlev** [karlfreeman/middleman-deploy#13]
I've followed to guide strictly and check with various ftp connections.

```
activate :deploy do |deploy|
  deploy.method = :ftp
  deploy.host = "ftp.servage.net"
  deploy.user = "trustpilot"
  deploy.password = "mypassword"
  deploy.path = "/www"
end

The error I get in my terminal


[~/Sit.../trustpilot/www] (www) $ middleman deploy
## Deploying via ftp to trustpilot@ftp.servage.net:/
/Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/middleman-deploy-0.0.9/lib/middleman-deploy/commands.rb:179:in `chdir': No such file or directory - build/ (Errno::ENOENT)
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/middleman-deploy-0.0.9/lib/middleman-deploy/commands.rb:179:in `deploy_ftp'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/middleman-deploy-0.0.9/lib/middleman-deploy/commands.rb:31:in `deploy'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/middleman-core-3.0.9/lib/middleman-core/cli.rb:77:in `method_missing'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/task.rb:29:in `run'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/task.rb:126:in `run'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/middleman-core-3.0.9/lib/middleman-core/cli.rb:22:in `start'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/gems/middleman-core-3.0.9/bin/middleman:18:in `<top (required)>'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/bin/middleman:19:in `load'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/bin/middleman:19:in `<main>'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/lajlev/.rvm/gems/ruby-1.9.3-p194@rails328/bin/ruby_noexec_wrapper:14:in `<main>'
´´´
```

**Comment by tobinfekkes** [comment]
I had all sorts of errors getting this to work, from the above error to "Could not find command 'deploy'."

After loads of Googling, simply changing the gemFile from (what the repo readme says to do)

`gem 'middleman-deploy', '~> 1.0'`

to 

`gem 'middleman-deploy', github: 'middleman-contrib/middleman-deploy', branch: 'master'`

fixed all the deploy issues. Of course, run `bundle build ` afterwards.

The middleman-deploy readme should probably be account for Middleman 4.0.
