### ISSUE TITLE
FTP deployments fail when FTP server needs TLS/SSL security settings.

### ISSUE THREAD

**Issue by jannisg** [karlfreeman/middleman-deploy#21]
Hi,

I'm trying to use `middleman-deploy` to push my builds directly to a client's FTP server. 
Unfortunately their FTP server does not use basic FTP nor do they use SFTP… instead it uses FTP with TLS/SSL settings.

Trying to connect/deploy to it at the moment produces the following error:

```
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/ftp.rb:298:in `getresp': 421 Sorry, cleartext sessions are not accepted on this server. (Net::FTPTempError)
    from /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/ftp.rb:325:in `block in sendcmd'
    from /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/ftp.rb:323:in `sendcmd'
    from /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/ftp.rb:430:in `block in login'
    from /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/ftp.rb:429:in `login'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/middleman-deploy-0.0.11/lib/middleman-deploy/commands.rb:181:in `deploy_ftp'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/middleman-deploy-0.0.11/lib/middleman-deploy/commands.rb:31:in `deploy'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/middleman-core-3.0.13/lib/middleman-core/cli.rb:77:in `method_missing'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/task.rb:29:in `run'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/task.rb:126:in `run'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/middleman-core-3.0.13/lib/middleman-core/cli.rb:22:in `start'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/gems/middleman-core-3.0.13/bin/middleman:18:in `<top (required)>'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/bin/middleman:23:in `load'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/bin/middleman:23:in `<main>'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/jannis/.rvm/gems/ruby-1.9.3-p194@racv/bin/ruby_noexec_wrapper:14:in `<main>'
```

I noticed that @benben did the initial pull request for the deploy FTP component so perhaps one of you could take a look at this when you get a moment or simply let me know whether this FTP+TLS/SSL isn't and won't be supported :).

**Comment by aaromnido** [comment]
I'm with the same problem trying to deploy in a iEII server. :(
Any solution is there?
