### ISSUE TITLE
Don't run livereload when deploying.

### ISSUE THREAD

**Issue by ghost** [karlfreeman/middleman-deploy#51]
When I run 'middleman deploy', it seems to run LiveReload when I use middleman-livereload in a project.

**Comment by Baires** [comment]
Same problem here

**Comment by parrots** [comment]
I'm creating an extension to auto-open a browser window to the live reload URL in dev, and I'm seeing the same thing for my extension that you guys see for live reload. I even check to make sure the environment isn't the dev environment out of paranoia and the browser is still opened *twice*. (doing all the right things like only activating the plugin during dev, etc). Similar to live reload, I don't see this issue occurring during the build command.

Snipit of my paranoia:

```
    app.ready do |builder|
      return unless app.environment == :development
      Launchy.open("http://0.0.0.0:4567")
    end

**Comment by tgdev** [comment]
I get the same thing and my activate :livereload is declared within a `configure :development do` block inside my config.rb. Commenting it out got around the issue but it's not ideal

**Comment by jahed** [comment]
Having a similar problem when trying to access Middleman::PreviewServer properties in the `development` configuration block.

By the looks of it, this is due to how options are retrieved through Middleman Deploy's CLI.

https://github.com/middleman-contrib/middleman-deploy/blob/master/lib/middleman-deploy/commands.rb#L62

```ruby
options = ::Middleman::Application.server.inst.options
```
`::Middleman::Application.server.inst` then triggers
```ruby
mm.run_hook :ready
```

Which will trigger the configuration block.

I'm kind of new to Ruby so I haven't looked into actually fixing it but this ticket in Middleman's repo may be relevant:
https://github.com/middleman/middleman/issues/781

Here's my stacktrace:

```
/home/jahed/projects/jahed-io/site/config.rb:26:in `block in initialize': uninitialized constant Middleman::PreviewServer (NameError)
        from /home/jahed/.gem/ruby/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
        from /home/jahed/.gem/ruby/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
        from /home/jahed/.gem/ruby/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
        from /home/jahed/.gem/ruby/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
        from /home/jahed/.gem/ruby/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/extensions.rb:166:in `initialize'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:204:in `initialize'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:56:in `new'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:56:in `inst'
        from /home/jahed/.gem/ruby/gems/middleman-deploy-1.0.0/lib/middleman-deploy/commands.rb:62:in `deploy_options'
        from /home/jahed/.gem/ruby/gems/middleman-deploy-1.0.0/lib/middleman-deploy/commands.rb:36:in `build_before'
        from /home/jahed/.gem/ruby/gems/middleman-deploy-1.0.0/lib/middleman-deploy/commands.rb:29:in `deploy'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/jahed/.gem/ruby/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
        from /home/jahed/.gem/ruby/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
        from /home/jahed/bin/middleman:23:in `load'
        from /home/jahed/bin/middleman:23:in `<main>'
```

**Comment by robertwbradford** [comment]
Does `activate :livereload` need to be moved into a :development configuration?

```
configure :development do
  activate :livereload
end
```

**Comment by jahed** [comment]
@robertwbradford We're doing that already. You can the `config.rb` we're using here:

https://github.com/unruly/unruly.github.io/blob/develop/config.rb
