### ISSUE TITLE
middleman-deploy breaks the building and the server operations (on windows)

### ISSUE THREAD

**Issue by uzian** [karlfreeman/middleman-deploy#66]
Hi!

Just by adding the line
gem "middleman-deploy" 
in the Gemfile, the "bundle exec middleman build" command breaks down and the middleman server gives the browser a "File not font" error.

Gemfile:

source 'http://rubygems.org'
gem "middleman", "~>3.3.3"
gem "middleman-livereload", "~> 3.1.0"
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]
gem "tzinfo-data", platforms: [:mswin, :mingw]
gem "slim"
gem "jquery-middleman"
gem "compass-rgbapng"
gem "bootstrap-sass", require: false
gem "middleman-favicon-maker"
gem "middleman-smusher"
gem "middleman-deploy"

The error at build is this:

C:\Sites\eg2016>bundle exec middleman build
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/pathname.rb:48:in `[]': no implicit conversion from nil to integer (TypeError)
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/pathname.rb:48:in`chop_basename'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/pathname.rb:101:in `cleanpath_aggressive'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/pathname.rb:89:in`cleanpath'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/pathname.rb:451:in `relative_path_from'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-core-3.3.3/lib/middleman-core/cli/build.rb:193:in`execute!'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-core-3.3.3/lib/middleman-core/cli/build.rb:128:in `invoke!'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/actions.rb:94:in`action'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-core-3.3.3/lib/middleman-core/cli/build.rb:70:in `build'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-core-3.3.3/lib/middleman-core/cli.rb:72:in`method_missing'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:126:in`run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-core-3.3.3/lib/middleman-core/cli.rb:20:in`start'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-core-3.3.3/bin/middleman:18:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/bin/middleman:23:in`load'
        from C:/RailsInstaller/Ruby1.9.3/bin/middleman:23:in `<main>'
## C:\Sites\eg2016>

And the middleman server gives this page, although it starts without errors and does not show any error when the browsers asks for the page

<html><body><h1>File Not Found</h1><p>/</p></body>

**Comment by mweirauch** [comment]
Any update on this? It's driving me nuts running middleman server on a repo in a shared linux windows environment. Allthough I can confirm the "solution" from @KingwenChow works.

**Comment by tgdev** [comment]
The above solution from @KingwenChow doesn't work for me. I thought it was a gem issue so cleared all my local gems then reinstalled sass, compass and bundler before re-running bundle install on my project.

Here's my gem file...

```source "http://rubygems.org"

# Middleman modules
gem "middleman", "~> 3.3.3"
gem "middleman-blog", "~> 3.5.3"
gem "middleman-livereload", "~> 3.3.4"
gem "middleman-minify-html"
gem "middleman-smusher"
gem 'middleman-deploy', '~> 1.0'

gem "wdm", :platforms => [:mswin, :mingw]
gem "tzinfo-data", platforms: [:mswin, :mingw]
# gem 'win32-file'

# For blog posts using markdown syntax
gem "kramdown"

# For feed.xml.builder
gem "builder"
```
